const CHECKED = 'CHECKED';
const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
const UN_CHECK = 'UN_CHECK';
const USERINFO = 'USERINFO';
const CURRENTUSERID = 'CURRENTUSERID';

export {
  CHECKED, FETCH_NEWS_FAILURE, UN_CHECK, USERINFO, CURRENTUSERID,
};
